name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:28.4.1

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
